### ISSUE TITLE
Errors in in v1.3

### ISSUE THREAD

**Issue by nadaa** [kreft/iDynoMiCS#74]
Hi, 
I'm a new user of iDynoMiCS , I installed all required software for iDynoMiCS . I imported v1.3 into eclipse and got may errors.
Can you please help!
![2015-11-01 14_20_21-java - eclipse sdk](https://cloud.githubusercontent.com/assets/1457075/10868829/a948297a-80a3-11e5-86f2-0e82bafe60c9.png)

Thanks

**Comment by roughhawkbit** [comment]
Hi Nadaa,

I think you may have an old version of Java installed on your computer: for iDynoMiCS v1.3 you need Java 1.8

Please let me know if this helps!

Best wishes,
Rob

![untitled](https://cloud.githubusercontent.com/assets/3294753/10869261/6cb2c468-80a1-11e5-80bc-8025666708e5.png)

**Comment by nadaa** [comment]
Thanks Rob for your helpful comment!
I think that worked well , and # of errors are decreased after adding jre1.8 to eclipse . Still encounter this error .. What do you think is the cause?



![2015-11-01 18_20_31-java - idynomics_src_utils_ziparchive java - eclipse sdk](https://cloud.githubusercontent.com/assets/1457075/10869923/48f987ee-80c6-11e5-84fc-04a31a62aaf2.png)

Regards,
Nada

**Comment by roughhawkbit** [comment]
Glad that helped!
The new error is a new one to me... can you show me the encodings settings?
Regards,
Rob

![untitled](https://cloud.githubusercontent.com/assets/3294753/10870177/22adf106-80bc-11e5-9142-4d919594a4db.png)

**Comment by nadaa** [comment]
UTF8

**Comment by roughhawkbit** [comment]
OK, maybe that last line ("Picked up...") is irrelevant. Googling it doesn't lead anywhere.

Could you show me the problems tab, like you did in your first post?

It might also be helpful if you could take the screenshot with the src folder open in the Package Explorer.

How are you trying to run iDynoMiCS? It's having trouble processing arguments, so have you tried running it from command line? The last section of [this](https://github.com/kreft/iDynoMiCS/wiki/Running-iDynoMiCS) page might be useful.

**Comment by nadaa** [comment]
Hi Rob.
V1.0 works fine with no error . I tried to run v1.3 using python got an error, have a look at bellow screenshots:
![2015-11-02 13_31_52-c__windows_system32_cmd_error exe](https://cloud.githubusercontent.com/assets/1457075/10880834/f877fdc2-8166-11e5-8298-8fdee232fce2.png)


![2015-11-02 13_22_34-java - idynomics_src_utils_ziparchive java - eclipse sdk](https://cloud.githubusercontent.com/assets/1457075/10880854/0d811578-8167-11e5-956c-171ce1df64d3.png)



Thank you

**Comment by nadaa** [comment]
Hi Rob.

I tried before to run the program from cmd ,but got an error that couldn't find the path of protocol. 
V1.0 works fine in eclipse, but got an exception at runtime "simulation error met"!

Have a look at the following screenshots:

cmd-python
![2015-11-02 13_22_34-java - idynomics_src_utils_ziparchive java - eclipse sdk](https://cloud.githubusercontent.com/assets/1457075/10881004/32a906d4-8168-11e5-8c2c-65edf0acf0b2.png)


v1.3
![2015-11-02 13_31_52-c__windows_system32_cmd_error exe](https://cloud.githubusercontent.com/assets/1457075/10881008/38ec98f8-8168-11e5-9921-67f844c8fffc.png)


v1.0
![2015-11-02 13_57_10-java - idynomics_src_utils_ziparchive java - eclipse sdk](https://cloud.githubusercontent.com/assets/1457075/10881096/ba23b424-8168-11e5-87a8-32d0e285294b.png)



Thank you.

**Comment by roughhawkbit** [comment]
Hi Nada,
As far as I can tell, the switch to Java 1.8 isn't quite complete - can you check the compiler compliance level is also at 1.8?

Thanks,
Rob

![untitled](https://cloud.githubusercontent.com/assets/3294753/10881201/c8237c90-8158-11e5-9255-dca52dc94288.png)

**Comment by nadaa** [comment]
What version of eclipse you have?

![2015-11-02 20_36_31-properties for idynomics](https://cloud.githubusercontent.com/assets/1457075/10890384/604de1c6-81a0-11e5-830c-b2d994f1b64d.png)


I tried to change to 1.8 compiler ,I'm trying to figure out how to add it , as it's not on the list

**Comment by nadaa** [comment]
I installed eclipse Luna , finally it works :)
![2015-11-02 22_38_03-java - eclipse](https://cloud.githubusercontent.com/assets/1457075/10893451/78c27620-81b1-11e5-9ed5-246565f43e30.png)

**Comment by roughhawkbit** [comment]
No problem, glad to hear it works! I think the latest version of Eclipse is actually Mars, so you might want to give that a go.
Regards,
Rob
