### ISSUE TITLE
number of iterations 

### ISSUE THREAD

**Issue by nadaa** [kreft/iDynoMiCS#75]
Hi,
 Why I got these selected iterations , isn't should be ordered as 0,1,2,3,.....etc, I used multi_species_multi_substrate_nitrification_EPS_2D protocol .

![2015-12-01 23_15_05-agent_state](https://cloud.githubusercontent.com/assets/1457075/11514508/84fbd936-9881-11e5-9ad3-1279a8d24976.png)

Thanks & regards,
Nada

**Comment by roughhawkbit** [comment]
**Response from Jan Kreft:**

Dear Nada,

Output is saved every 20 iterations because of the settings in the protocol file, where outputPeriod is 2 hours and the timeStep is 0.1 hours:

``` xml
<simulator>
    <param name="restartPreviousRun">false</param>
    <param name="randomSeed">42</param>
     <param name="outputPeriod" unit="hour">2</param>
     <timeStep>
           <param name="adaptive">true</param>
           <param name="timeStepIni" unit="hour">0.1</param>
           <param name="timeStepMin" unit="hour">0.025</param>
           <param name="timeStepMax" unit="hour">1</param>
           <param name="endOfSimulation" unit="day">3</param>
     </timeStep>
     <param name="agentTimeStep" unit="hour">0.05</param>
</simulator>
```
Hope that helps,

Jan

**Comment by kreft** [comment]
Wasn't an issue, results are as expected given protocol settings.
